<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
		"http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<title>nfs_trades</title>
<style type="text/css">
	hr.pme-hr		     { border: 0px solid; padding: 0px; margin: 0px; border-top-width: 1px; height: 1px; }
	table.pme-main 	     { border: #004d9c 1px solid; border-collapse: collapse; border-spacing: 0px; width: 100%; }
	table.pme-navigation { border: #004d9c 0px solid; border-collapse: collapse; border-spacing: 0px; width: 100%; }
	td.pme-navigation-0, td.pme-navigation-1 { white-space: nowrap; }
	th.pme-header	     { border: #004d9c 1px solid; padding: 4px; background: #add8e6; }
	td.pme-key-0, td.pme-value-0, td.pme-help-0, td.pme-navigation-0, td.pme-cell-0,
	td.pme-key-1, td.pme-value-1, td.pme-help-0, td.pme-navigation-1, td.pme-cell-1,
	td.pme-sortinfo, td.pme-filter { border: #004d9c 1px solid; padding: 3px; }
	td.pme-buttons { text-align: left;   }
	td.pme-message { text-align: center; }
	td.pme-stats   { text-align: right;  }
</style>
</head>
<body>
<h3>nfs_trades</h3>
<?php

/*
 * IMPORTANT NOTE: This generated file contains only a subset of huge amount
 * of options that can be used with phpMyEdit. To get information about all
 * features offered by phpMyEdit, check official documentation. It is available
 * online and also for download on phpMyEdit project management page:
 *
 * http://platon.sk/projects/main_page.php?project_id=5
 *
 * This file was generated by:
 *
 *                    phpMyEdit version: 5.7.1
 *       phpMyEdit.class.php core class: 1.204
 *            phpMyEditSetup.php script: 1.50
 *              generating setup script: 1.50
 */

// MySQL host name, user name, password, database, and table
$opts['hn'] = 'localhost';
$opts['un'] = 'newadmin';
$opts['pw'] = 'newpassword';
$opts['db'] = 'warehouse';
$opts['tb'] = 'nfs_trades';

// Name of field which is the unique key
$opts['key'] = 'trad_auto_id';

// Type of key field (int/real/string/date etc.)
$opts['key_type'] = 'int';

// Sorting field(s)
$opts['sort_field'] = array('trad_auto_id');

// Number of records to display on the screen
// Value of -1 lists all records in a table
$opts['inc'] = 15;

// Options you wish to give the users
// A - add,  C - change, P - copy, V - view, D - delete,
// F - filter, I - initial sort suppressed
$opts['options'] = 'ACPVDF';

// Number of lines to display on multiple selection filters
$opts['multiple'] = '4';

// Navigation style: B - buttons (default), T - text links, G - graphic links
// Buttons position: U - up, D - down (default)
$opts['navigation'] = 'DB';

// Display special page elements
$opts['display'] = array(
	'form'  => true,
	'query' => true,
	'sort'  => true,
	'time'  => true,
	'tabs'  => true
);

// Set default prefixes for variables
$opts['js']['prefix']               = 'PME_js_';
$opts['dhtml']['prefix']            = 'PME_dhtml_';
$opts['cgi']['prefix']['operation'] = 'PME_op_';
$opts['cgi']['prefix']['sys']       = 'PME_sys_';
$opts['cgi']['prefix']['data']      = 'PME_data_';

/* Get the user's default language and use it if possible or you can
   specify particular one you want to use. Refer to official documentation
   for list of available languages. */
$opts['language'] = $_SERVER['HTTP_ACCEPT_LANGUAGE'] . '-UTF8';

/* Table-level filter capability. If set, it is included in the WHERE clause
   of any generated SELECT statement in SQL query. This gives you ability to
   work only with subset of data from table.

$opts['filters'] = "column1 like '%11%' AND column2<17";
$opts['filters'] = "section_id = 9";
$opts['filters'] = "PMEtable0.sessions_count > 200";
*/

/* Field definitions
   
Fields will be displayed left to right on the screen in the order in which they
appear in generated list. Here are some most used field options documented.

['name'] is the title used for column headings, etc.;
['maxlen'] maximum length to display add/edit/search input boxes
['trimlen'] maximum length of string content to display in row listing
['width'] is an optional display width specification for the column
          e.g.  ['width'] = '100px';
['mask'] a string that is used by sprintf() to format field output
['sort'] true or false; means the users may sort the display on this column
['strip_tags'] true or false; whether to strip tags from content
['nowrap'] true or false; whether this field should get a NOWRAP
['select'] T - text, N - numeric, D - drop-down, M - multiple selection
['options'] optional parameter to control whether a field is displayed
  L - list, F - filter, A - add, C - change, P - copy, D - delete, V - view
            Another flags are:
            R - indicates that a field is read only
            W - indicates that a field is a password field
            H - indicates that a field is to be hidden and marked as hidden
['URL'] is used to make a field 'clickable' in the display
        e.g.: 'mailto:$value', 'http://$value' or '$page?stuff';
['URLtarget']  HTML target link specification (for example: _blank)
['textarea']['rows'] and/or ['textarea']['cols']
  specifies a textarea is to be used to give multi-line input
  e.g. ['textarea']['rows'] = 5; ['textarea']['cols'] = 10
['values'] restricts user input to the specified constants,
           e.g. ['values'] = array('A','B','C') or ['values'] = range(1,99)
['values']['table'] and ['values']['column'] restricts user input
  to the values found in the specified column of another table
['values']['description'] = 'desc_column'
  The optional ['values']['description'] field allows the value(s) displayed
  to the user to be different to those in the ['values']['column'] field.
  This is useful for giving more meaning to column values. Multiple
  descriptions fields are also possible. Check documentation for this.
*/

$opts['fdd']['trad_auto_id'] = array(
  'name'     => 'Trad auto ID',
  'select'   => 'T',
  'options'  => 'AVCPDR', // auto increment
  'maxlen'   => 20,
  'default'  => '0',
  'sort'     => true
);
$opts['fdd']['trad_firm'] = array(
  'name'     => 'Trad firm',
  'select'   => 'T',
  'maxlen'   => 4,
  'sort'     => true
);
$opts['fdd']['trad_buy_sell'] = array(
  'name'     => 'Trad buy sell',
  'select'   => 'T',
  'maxlen'   => 12,
  'sort'     => true
);
$opts['fdd']['trad_trade_date'] = array(
  'name'     => 'Trad trade date',
  'select'   => 'T',
  'maxlen'   => 10,
  'sort'     => true
);
$opts['fdd']['trad_settle_date'] = array(
  'name'     => 'Trad settle date',
  'select'   => 'T',
  'maxlen'   => 10,
  'sort'     => true
);
$opts['fdd']['trad_market_code'] = array(
  'name'     => 'Trad market code',
  'select'   => 'T',
  'maxlen'   => 1,
  'sort'     => true
);
$opts['fdd']['trad_blotter_code'] = array(
  'name'     => 'Trad blotter code',
  'select'   => 'T',
  'maxlen'   => 1,
  'sort'     => true
);
$opts['fdd']['trad_cancel_code'] = array(
  'name'     => 'Trad cancel code',
  'select'   => 'T',
  'maxlen'   => 1,
  'sort'     => true
);
$opts['fdd']['trad_streetside_code'] = array(
  'name'     => 'Trad streetside code',
  'select'   => 'T',
  'maxlen'   => 1,
  'sort'     => true
);
$opts['fdd']['trad_due_bill'] = array(
  'name'     => 'Trad due bill',
  'select'   => 'T',
  'maxlen'   => 1,
  'sort'     => true
);
$opts['fdd']['trad_correction_code'] = array(
  'name'     => 'Trad correction code',
  'select'   => 'T',
  'maxlen'   => 1,
  'sort'     => true
);
$opts['fdd']['trad_branch'] = array(
  'name'     => 'Trad branch',
  'select'   => 'T',
  'maxlen'   => 3,
  'sort'     => true
);
$opts['fdd']['trad_account_number'] = array(
  'name'     => 'Trad account number',
  'select'   => 'T',
  'maxlen'   => 6,
  'sort'     => true
);
$opts['fdd']['trad_full_account_number'] = array(
  'name'     => 'Trad full account number',
  'select'   => 'T',
  'maxlen'   => 9,
  'sort'     => true
);
$opts['fdd']['trad_account_type'] = array(
  'name'     => 'Trad account type',
  'select'   => 'T',
  'maxlen'   => 1,
  'sort'     => true
);
$opts['fdd']['trad_country_code'] = array(
  'name'     => 'Trad country code',
  'select'   => 'T',
  'maxlen'   => 2,
  'sort'     => true
);
$opts['fdd']['trad_cusip'] = array(
  'name'     => 'Trad cusip',
  'select'   => 'T',
  'maxlen'   => 9,
  'sort'     => true
);
$opts['fdd']['trad_basis_price_code'] = array(
  'name'     => 'Trad basis price code',
  'select'   => 'T',
  'maxlen'   => 1,
  'sort'     => true
);
$opts['fdd']['trad_run_date'] = array(
  'name'     => 'Trad run date',
  'select'   => 'T',
  'maxlen'   => 10,
  'sort'     => true
);
$opts['fdd']['trad_trade_reference_number'] = array(
  'name'     => 'Trad trade reference number',
  'select'   => 'T',
  'maxlen'   => 11,
  'sort'     => true
);
$opts['fdd']['trad_user_reference'] = array(
  'name'     => 'Trad user reference',
  'select'   => 'T',
  'maxlen'   => 11,
  'sort'     => true
);
$opts['fdd']['trad_canceled_combined_ref'] = array(
  'name'     => 'Trad canceled combined ref',
  'select'   => 'T',
  'maxlen'   => 11,
  'sort'     => true
);
$opts['fdd']['trad_batch'] = array(
  'name'     => 'Trad batch',
  'select'   => 'T',
  'maxlen'   => 5,
  'sort'     => true
);
$opts['fdd']['trad_count'] = array(
  'name'     => 'Trad count',
  'select'   => 'T',
  'maxlen'   => 6,
  'sort'     => true
);
$opts['fdd']['trad_symbol'] = array(
  'name'     => 'Trad symbol',
  'select'   => 'T',
  'maxlen'   => 16,
  'sort'     => true
);
$opts['fdd']['trad_sec_type'] = array(
  'name'     => 'Trad sec type',
  'select'   => 'T',
  'maxlen'   => 1,
  'sort'     => true
);
$opts['fdd']['trad_sec_type_modifier'] = array(
  'name'     => 'Trad sec type modifier',
  'select'   => 'T',
  'maxlen'   => 1,
  'sort'     => true
);
$opts['fdd']['trad_sec_type_calc'] = array(
  'name'     => 'Trad sec type calc',
  'select'   => 'T',
  'maxlen'   => 1,
  'sort'     => true
);
$opts['fdd']['trad_cns'] = array(
  'name'     => 'Trad cns',
  'select'   => 'T',
  'maxlen'   => 1,
  'sort'     => true
);
$opts['fdd']['trad_primary_exchange'] = array(
  'name'     => 'Trad primary exchange',
  'select'   => 'T',
  'maxlen'   => 2,
  'sort'     => true
);
$opts['fdd']['trad_dtc_eligibility_code'] = array(
  'name'     => 'Trad dtc eligibility code',
  'select'   => 'T',
  'maxlen'   => 1,
  'sort'     => true
);
$opts['fdd']['trad_foreign_code'] = array(
  'name'     => 'Trad foreign code',
  'select'   => 'T',
  'maxlen'   => 1,
  'sort'     => true
);
$opts['fdd']['trad_registered_rep'] = array(
  'name'     => 'Trad registered rep',
  'select'   => 'T',
  'maxlen'   => 3,
  'sort'     => true
);
$opts['fdd']['trad_state_country_code'] = array(
  'name'     => 'Trad state country code',
  'select'   => 'T',
  'maxlen'   => 3,
  'sort'     => true
);
$opts['fdd']['trad_ny_tax'] = array(
  'name'     => 'Trad ny tax',
  'select'   => 'T',
  'maxlen'   => 1,
  'sort'     => true
);
$opts['fdd']['trad_sec_instructions'] = array(
  'name'     => 'Trad sec instructions',
  'select'   => 'T',
  'maxlen'   => 1,
  'sort'     => true
);
$opts['fdd']['trad_service'] = array(
  'name'     => 'Trad service',
  'select'   => 'T',
  'maxlen'   => 1,
  'sort'     => true
);
$opts['fdd']['trad_parent_account'] = array(
  'name'     => 'Trad parent account',
  'select'   => 'T',
  'maxlen'   => 9,
  'sort'     => true
);
$opts['fdd']['trad_agency_code'] = array(
  'name'     => 'Trad agency code',
  'select'   => 'T',
  'maxlen'   => 8,
  'sort'     => true
);
$opts['fdd']['trad_mode_del'] = array(
  'name'     => 'Trad mode del',
  'select'   => 'T',
  'maxlen'   => 1,
  'sort'     => true
);
$opts['fdd']['trad_proceed_instructions'] = array(
  'name'     => 'Trad proceed instructions',
  'select'   => 'T',
  'maxlen'   => 1,
  'sort'     => true
);
$opts['fdd']['trad_income_instructions'] = array(
  'name'     => 'Trad income instructions',
  'select'   => 'T',
  'maxlen'   => 1,
  'sort'     => true
);
$opts['fdd']['trad_sales_prod'] = array(
  'name'     => 'Trad sales prod',
  'select'   => 'T',
  'maxlen'   => 1,
  'sort'     => true
);
$opts['fdd']['trad_trade_unit'] = array(
  'name'     => 'Trad trade unit',
  'select'   => 'T',
  'maxlen'   => 1,
  'sort'     => true
);
$opts['fdd']['trad_short_name'] = array(
  'name'     => 'Trad short name',
  'select'   => 'T',
  'maxlen'   => 10,
  'sort'     => true
);
$opts['fdd']['trad_acct_classification'] = array(
  'name'     => 'Trad acct classification',
  'select'   => 'T',
  'maxlen'   => 2,
  'sort'     => true
);
$opts['fdd']['trad_citizen_code'] = array(
  'name'     => 'Trad citizen code',
  'select'   => 'T',
  'maxlen'   => 1,
  'sort'     => true
);
$opts['fdd']['trad_country_of_tax_residency'] = array(
  'name'     => 'Trad country of tax residency',
  'select'   => 'T',
  'maxlen'   => 3,
  'sort'     => true
);
$opts['fdd']['trad_transfer_legend_code'] = array(
  'name'     => 'Trad transfer legend code',
  'select'   => 'T',
  'maxlen'   => 1,
  'sort'     => true
);
$opts['fdd']['trad_marketmaker_code'] = array(
  'name'     => 'Trad marketmaker code',
  'select'   => 'T',
  'maxlen'   => 1,
  'sort'     => true
);
$opts['fdd']['trad_rr_penalty'] = array(
  'name'     => 'Trad rr penalty',
  'select'   => 'T',
  'maxlen'   => 1,
  'sort'     => true
);
$opts['fdd']['trad_minor_exec_broker'] = array(
  'name'     => 'Trad minor exec broker',
  'select'   => 'T',
  'maxlen'   => 4,
  'sort'     => true
);
$opts['fdd']['trad_minor_clearing_broker'] = array(
  'name'     => 'Trad minor clearing broker',
  'select'   => 'T',
  'maxlen'   => 4,
  'sort'     => true
);
$opts['fdd']['trad_offset_account'] = array(
  'name'     => 'Trad offset account',
  'select'   => 'T',
  'maxlen'   => 10,
  'sort'     => true
);
$opts['fdd']['trad_offset_shortname'] = array(
  'name'     => 'Trad offset shortname',
  'select'   => 'T',
  'maxlen'   => 10,
  'sort'     => true
);
$opts['fdd']['trad_offset_rr'] = array(
  'name'     => 'Trad offset rr',
  'select'   => 'T',
  'maxlen'   => 3,
  'sort'     => true
);
$opts['fdd']['trad_offset_commission'] = array(
  'name'     => 'Trad offset commission',
  'select'   => 'T',
  'maxlen'   => 9,
  'sort'     => true
);
$opts['fdd']['trad_source'] = array(
  'name'     => 'Trad source',
  'select'   => 'T',
  'maxlen'   => 1,
  'sort'     => true
);
$opts['fdd']['trad_type_of_order'] = array(
  'name'     => 'Trad type of order',
  'select'   => 'T',
  'maxlen'   => 1,
  'sort'     => true
);
$opts['fdd']['trad_confirm_print'] = array(
  'name'     => 'Trad confirm print',
  'select'   => 'T',
  'maxlen'   => 1,
  'sort'     => true
);
$opts['fdd']['trad_commission_accumulation'] = array(
  'name'     => 'Trad commission accumulation',
  'select'   => 'T',
  'maxlen'   => 1,
  'sort'     => true
);
$opts['fdd']['trad_commission_schedule'] = array(
  'name'     => 'Trad commission schedule',
  'select'   => 'T',
  'maxlen'   => 2,
  'sort'     => true
);
$opts['fdd']['trad_blotter_override_code'] = array(
  'name'     => 'Trad blotter override code',
  'select'   => 'T',
  'maxlen'   => 1,
  'sort'     => true
);
$opts['fdd']['trad_nscc_code'] = array(
  'name'     => 'Trad nscc code',
  'select'   => 'T',
  'maxlen'   => 1,
  'sort'     => true
);
$opts['fdd']['trad_commission_concession_code'] = array(
  'name'     => 'Trad commission concession code',
  'select'   => 'T',
  'maxlen'   => 1,
  'sort'     => true
);
$opts['fdd']['trad_quantity'] = array(
  'name'     => 'Trad quantity',
  'select'   => 'T',
  'maxlen'   => 18,
  'sort'     => true
);
$opts['fdd']['trad_price'] = array(
  'name'     => 'Trad price',
  'select'   => 'T',
  'maxlen'   => 20,
  'sort'     => true
);
$opts['fdd']['trad_alphaprice_dollar'] = array(
  'name'     => 'Trad alphaprice dollar',
  'select'   => 'T',
  'maxlen'   => 9,
  'sort'     => true
);
$opts['fdd']['trad_alphaprice_space'] = array(
  'name'     => 'Trad alphaprice space',
  'select'   => 'T',
  'maxlen'   => 1,
  'sort'     => true
);
$opts['fdd']['trad_alphaprice_fraction'] = array(
  'name'     => 'Trad alphaprice fraction',
  'select'   => 'T',
  'maxlen'   => 9,
  'sort'     => true
);
$opts['fdd']['trad_plus_minus'] = array(
  'name'     => 'Trad plus minus',
  'select'   => 'T',
  'maxlen'   => 20,
  'sort'     => true
);
$opts['fdd']['trad_principal'] = array(
  'name'     => 'Trad principal',
  'select'   => 'T',
  'maxlen'   => 17,
  'sort'     => true
);
$opts['fdd']['trad_accrued_interest'] = array(
  'name'     => 'Trad accrued interest',
  'select'   => 'T',
  'maxlen'   => 14,
  'sort'     => true
);
$opts['fdd']['trad_trade_commission'] = array(
  'name'     => 'Trad trade commission',
  'select'   => 'T',
  'maxlen'   => 12,
  'sort'     => true
);
$opts['fdd']['trad_state_tax'] = array(
  'name'     => 'Trad state tax',
  'select'   => 'T',
  'maxlen'   => 10,
  'sort'     => true
);
$opts['fdd']['trad_sec_fee'] = array(
  'name'     => 'Trad sec fee',
  'select'   => 'T',
  'maxlen'   => 10,
  'sort'     => true
);
$opts['fdd']['trad_service_charge_misc_fee'] = array(
  'name'     => 'Trad service charge misc fee',
  'select'   => 'T',
  'maxlen'   => 12,
  'sort'     => true
);
$opts['fdd']['trad_net'] = array(
  'name'     => 'Trad net',
  'select'   => 'T',
  'maxlen'   => 17,
  'sort'     => true
);
$opts['fdd']['trad_brokerage'] = array(
  'name'     => 'Trad brokerage',
  'select'   => 'T',
  'maxlen'   => 12,
  'sort'     => true
);
$opts['fdd']['trad_trade_concession'] = array(
  'name'     => 'Trad trade concession',
  'select'   => 'T',
  'maxlen'   => 12,
  'sort'     => true
);
$opts['fdd']['trad_standard_commission'] = array(
  'name'     => 'Trad standard commission',
  'select'   => 'T',
  'maxlen'   => 12,
  'sort'     => true
);
$opts['fdd']['trad_sec_desc_1'] = array(
  'name'     => 'Trad sec desc 1',
  'select'   => 'T',
  'maxlen'   => 20,
  'sort'     => true
);
$opts['fdd']['trad_sec_desc_2'] = array(
  'name'     => 'Trad sec desc 2',
  'select'   => 'T',
  'maxlen'   => 20,
  'sort'     => true
);
$opts['fdd']['trad_sec_desc_3'] = array(
  'name'     => 'Trad sec desc 3',
  'select'   => 'T',
  'maxlen'   => 20,
  'sort'     => true
);
$opts['fdd']['trad_sec_desc_4'] = array(
  'name'     => 'Trad sec desc 4',
  'select'   => 'T',
  'maxlen'   => 20,
  'sort'     => true
);
$opts['fdd']['trad_sec_desc_5'] = array(
  'name'     => 'Trad sec desc 5',
  'select'   => 'T',
  'maxlen'   => 20,
  'sort'     => true
);
$opts['fdd']['trad_sec_desc_6'] = array(
  'name'     => 'Trad sec desc 6',
  'select'   => 'T',
  'maxlen'   => 20,
  'sort'     => true
);
$opts['fdd']['trad_sec_desc_7'] = array(
  'name'     => 'Trad sec desc 7',
  'select'   => 'T',
  'maxlen'   => 20,
  'sort'     => true
);
$opts['fdd']['trad_sec_desc_8'] = array(
  'name'     => 'Trad sec desc 8',
  'select'   => 'T',
  'maxlen'   => 20,
  'sort'     => true
);
$opts['fdd']['trad_sec_desc_9'] = array(
  'name'     => 'Trad sec desc 9',
  'select'   => 'T',
  'maxlen'   => 20,
  'sort'     => true
);
$opts['fdd']['trad_confirm_legend_code'] = array(
  'name'     => 'Trad confirm legend code',
  'select'   => 'T',
  'maxlen'   => 8,
  'sort'     => true
);
$opts['fdd']['trad_rr_exec_rep'] = array(
  'name'     => 'Trad rr exec rep',
  'select'   => 'T',
  'maxlen'   => 3,
  'sort'     => true
);
$opts['fdd']['trad_comm_discount_percent'] = array(
  'name'     => 'Trad comm discount percent',
  'select'   => 'T',
  'maxlen'   => 12,
  'sort'     => true
);
$opts['fdd']['trad_strike_price'] = array(
  'name'     => 'Trad strike price',
  'select'   => 'T',
  'maxlen'   => 11,
  'sort'     => true
);
$opts['fdd']['trad_sec_group_code'] = array(
  'name'     => 'Trad sec group code',
  'select'   => 'T',
  'maxlen'   => 1,
  'sort'     => true
);
$opts['fdd']['trad_due_bill_multiplier'] = array(
  'name'     => 'Trad due bill multiplier',
  'select'   => 'T',
  'maxlen'   => 7,
  'sort'     => true
);
$opts['fdd']['trad_d_market_code'] = array(
  'name'     => 'Trad d market code',
  'select'   => 'T',
  'maxlen'   => 1,
  'sort'     => true
);
$opts['fdd']['trad_d_blotter_code'] = array(
  'name'     => 'Trad d blotter code',
  'select'   => 'T',
  'maxlen'   => 1,
  'sort'     => true
);
$opts['fdd']['trad_commission_concession_code_a'] = array(
  'name'     => 'Trad commission concession code a',
  'select'   => 'T',
  'maxlen'   => 1,
  'sort'     => true
);
$opts['fdd']['trad_commission_preference_code'] = array(
  'name'     => 'Trad commission preference code',
  'select'   => 'T',
  'maxlen'   => 1,
  'sort'     => true
);
$opts['fdd']['trad_fund_load_override'] = array(
  'name'     => 'Trad fund load override',
  'select'   => 'T',
  'maxlen'   => 6,
  'sort'     => true
);
$opts['fdd']['trad_quantity_type'] = array(
  'name'     => 'Trad quantity type',
  'select'   => 'T',
  'maxlen'   => 1,
  'sort'     => true
);
$opts['fdd']['trad_confirm_line'] = array(
  'name'     => 'Trad confirm line',
  'select'   => 'T',
  'maxlen'   => 1,
  'sort'     => true
);
$opts['fdd']['trad_exchange_line'] = array(
  'name'     => 'Trad exchange line',
  'select'   => 'T',
  'maxlen'   => 1,
  'sort'     => true
);
$opts['fdd']['trad_yield'] = array(
  'name'     => 'Trad yield',
  'select'   => 'T',
  'maxlen'   => 7,
  'sort'     => true
);
$opts['fdd']['trad_yield_type'] = array(
  'name'     => 'Trad yield type',
  'select'   => 'T',
  'maxlen'   => 1,
  'sort'     => true
);
$opts['fdd']['trad_yield_date'] = array(
  'name'     => 'Trad yield date',
  'select'   => 'T',
  'maxlen'   => 7,
  'sort'     => true
);
$opts['fdd']['trad_yield_price'] = array(
  'name'     => 'Trad yield price',
  'select'   => 'T',
  'maxlen'   => 8,
  'sort'     => true
);
$opts['fdd']['trad_trading_away_code'] = array(
  'name'     => 'Trad trading away code',
  'select'   => 'T',
  'maxlen'   => 1,
  'sort'     => true
);
$opts['fdd']['trad_major_clearing_broker'] = array(
  'name'     => 'Trad major clearing broker',
  'select'   => 'T',
  'maxlen'   => 4,
  'sort'     => true
);
$opts['fdd']['trad_major_exec_broker'] = array(
  'name'     => 'Trad major exec broker',
  'select'   => 'T',
  'maxlen'   => 4,
  'sort'     => true
);
$opts['fdd']['trad_execution_time'] = array(
  'name'     => 'Trad execution time',
  'select'   => 'T',
  'maxlen'   => 4,
  'sort'     => true
);
$opts['fdd']['trad_branch_a'] = array(
  'name'     => 'Trad branch a',
  'select'   => 'T',
  'maxlen'   => 3,
  'sort'     => true
);
$opts['fdd']['trad_irs_no'] = array(
  'name'     => 'Trad irs no',
  'select'   => 'T',
  'maxlen'   => 9,
  'sort'     => true
);
$opts['fdd']['trad_market_place'] = array(
  'name'     => 'Trad market place',
  'select'   => 'T',
  'maxlen'   => 5,
  'sort'     => true
);
$opts['fdd']['trad_market_sequence'] = array(
  'name'     => 'Trad market sequence',
  'select'   => 'T',
  'maxlen'   => 6,
  'sort'     => true
);
$opts['fdd']['trad_market_override'] = array(
  'name'     => 'Trad market override',
  'select'   => 'T',
  'maxlen'   => 1,
  'sort'     => true
);
$opts['fdd']['trad_time_in_force'] = array(
  'name'     => 'Trad time in force',
  'select'   => 'T',
  'maxlen'   => 1,
  'sort'     => true
);
$opts['fdd']['trad_auto_exec_code'] = array(
  'name'     => 'Trad auto exec code',
  'select'   => 'T',
  'maxlen'   => 1,
  'sort'     => true
);
$opts['fdd']['trad_issuer'] = array(
  'name'     => 'Trad issuer',
  'select'   => 'T',
  'maxlen'   => 6,
  'sort'     => true
);
$opts['fdd']['trad_issuer_type'] = array(
  'name'     => 'Trad issuer type',
  'select'   => 'T',
  'maxlen'   => 2,
  'sort'     => true
);
$opts['fdd']['trad_bond_trader'] = array(
  'name'     => 'Trad bond trader',
  'select'   => 'T',
  'maxlen'   => 4,
  'sort'     => true
);
$opts['fdd']['trad_bond_class_code'] = array(
  'name'     => 'Trad bond class code',
  'select'   => 'T',
  'maxlen'   => 1,
  'sort'     => true
);
$opts['fdd']['trad_additional_markup'] = array(
  'name'     => 'Trad additional markup',
  'select'   => 'T',
  'maxlen'   => 12,
  'sort'     => true
);
$opts['fdd']['trad_terminal_id'] = array(
  'name'     => 'Trad terminal ID',
  'select'   => 'T',
  'maxlen'   => 4,
  'sort'     => true
);
$opts['fdd']['trad_signon_rep_location'] = array(
  'name'     => 'Trad signon rep location',
  'select'   => 'T',
  'maxlen'   => 5,
  'sort'     => true
);
$opts['fdd']['trad_rr_signon_rep'] = array(
  'name'     => 'Trad rr signon rep',
  'select'   => 'T',
  'maxlen'   => 3,
  'sort'     => true
);
$opts['fdd']['trad_rr_owning_rep'] = array(
  'name'     => 'Trad rr owning rep',
  'select'   => 'T',
  'maxlen'   => 3,
  'sort'     => true
);
$opts['fdd']['trad_fund_load_percent'] = array(
  'name'     => 'Trad fund load percent',
  'select'   => 'T',
  'maxlen'   => 6,
  'sort'     => true
);
$opts['fdd']['trad_product_code'] = array(
  'name'     => 'Trad product code',
  'select'   => 'T',
  'maxlen'   => 12,
  'sort'     => true
);
$opts['fdd']['trad_trading_flat_code'] = array(
  'name'     => 'Trad trading flat code',
  'select'   => 'T',
  'maxlen'   => 1,
  'sort'     => true
);
$opts['fdd']['trad_12B1_code'] = array(
  'name'     => 'Trad 12B1 code',
  'select'   => 'T',
  'maxlen'   => 1,
  'sort'     => true
);
$opts['fdd']['trad_additional_fee_code_1'] = array(
  'name'     => 'Trad additional fee code 1',
  'select'   => 'T',
  'maxlen'   => 2,
  'sort'     => true
);
$opts['fdd']['trad_additional_fee_1'] = array(
  'name'     => 'Trad additional fee 1',
  'select'   => 'T',
  'maxlen'   => 11,
  'sort'     => true
);
$opts['fdd']['trad_additional_fee_code_2'] = array(
  'name'     => 'Trad additional fee code 2',
  'select'   => 'T',
  'maxlen'   => 2,
  'sort'     => true
);
$opts['fdd']['trad_additional_fee_2'] = array(
  'name'     => 'Trad additional fee 2',
  'select'   => 'T',
  'maxlen'   => 11,
  'sort'     => true
);
$opts['fdd']['trad_additional_fee_code_3'] = array(
  'name'     => 'Trad additional fee code 3',
  'select'   => 'T',
  'maxlen'   => 2,
  'sort'     => true
);
$opts['fdd']['trad_additional_fee_3'] = array(
  'name'     => 'Trad additional fee 3',
  'select'   => 'T',
  'maxlen'   => 11,
  'sort'     => true
);
$opts['fdd']['trad_additional_fee_code_4'] = array(
  'name'     => 'Trad additional fee code 4',
  'select'   => 'T',
  'maxlen'   => 2,
  'sort'     => true
);
$opts['fdd']['trad_additional_fee_4'] = array(
  'name'     => 'Trad additional fee 4',
  'select'   => 'T',
  'maxlen'   => 11,
  'sort'     => true
);
$opts['fdd']['trad_additional_fee_code_5'] = array(
  'name'     => 'Trad additional fee code 5',
  'select'   => 'T',
  'maxlen'   => 2,
  'sort'     => true
);
$opts['fdd']['trad_additional_fee_5'] = array(
  'name'     => 'Trad additional fee 5',
  'select'   => 'T',
  'maxlen'   => 11,
  'sort'     => true
);
$opts['fdd']['trad_additional_fee_code_6'] = array(
  'name'     => 'Trad additional fee code 6',
  'select'   => 'T',
  'maxlen'   => 2,
  'sort'     => true
);
$opts['fdd']['trad_additional_fee_6'] = array(
  'name'     => 'Trad additional fee 6',
  'select'   => 'T',
  'maxlen'   => 11,
  'sort'     => true
);
$opts['fdd']['trad_institutional_third_party'] = array(
  'name'     => 'Trad institutional third party',
  'select'   => 'T',
  'maxlen'   => 4,
  'sort'     => true
);
$opts['fdd']['trad_institutional_lot_number'] = array(
  'name'     => 'Trad institutional lot number',
  'select'   => 'T',
  'maxlen'   => 4,
  'sort'     => true
);
$opts['fdd']['trad_bord_tord_code'] = array(
  'name'     => 'Trad bord tord code',
  'select'   => 'T',
  'maxlen'   => 1,
  'sort'     => true
);
$opts['fdd']['trad_mutual_fund_dtc_number'] = array(
  'name'     => 'Trad mutual fund dtc number',
  'select'   => 'T',
  'maxlen'   => 4,
  'sort'     => true
);
$opts['fdd']['trad_trade_entry'] = array(
  'name'     => 'Trad trade entry',
  'select'   => 'T',
  'maxlen'   => 6,
  'sort'     => true
);
$opts['fdd']['trad_entry_sequence_number'] = array(
  'name'     => 'Trad entry sequence number',
  'select'   => 'T',
  'maxlen'   => 5,
  'sort'     => true
);
$opts['fdd']['trad_solicited_code'] = array(
  'name'     => 'Trad solicited code',
  'select'   => 'T',
  'maxlen'   => 1,
  'sort'     => true
);
$opts['fdd']['trad_elec_trade_id'] = array(
  'name'     => 'Trad elec trade ID',
  'select'   => 'T',
  'maxlen'   => 3,
  'sort'     => true
);
$opts['fdd']['trad_rollup_count'] = array(
  'name'     => 'Trad rollup count',
  'select'   => 'T',
  'maxlen'   => 3,
  'sort'     => true
);
$opts['fdd']['trad_revenue_clearing_charge_amt'] = array(
  'name'     => 'Trad revenue clearing charge amt',
  'select'   => 'T',
  'maxlen'   => 9,
  'sort'     => true
);
$opts['fdd']['trad_revenue_misc_fee_amt'] = array(
  'name'     => 'Trad revenue misc fee amt',
  'select'   => 'T',
  'maxlen'   => 9,
  'sort'     => true
);
$opts['fdd']['trad_product_level'] = array(
  'name'     => 'Trad product level',
  'select'   => 'T',
  'maxlen'   => 2,
  'sort'     => true
);
$opts['fdd']['trad_concession_code'] = array(
  'name'     => 'Trad concession code',
  'select'   => 'T',
  'maxlen'   => 1,
  'sort'     => true
);
$opts['fdd']['trad_purchase_type_code'] = array(
  'name'     => 'Trad purchase type code',
  'select'   => 'T',
  'maxlen'   => 2,
  'sort'     => true
);
$opts['fdd']['trad_trade_definition_type'] = array(
  'name'     => 'Trad trade definition type',
  'select'   => 'T',
  'maxlen'   => 1,
  'sort'     => true
);
$opts['fdd']['trad_trade_definition_trade_id'] = array(
  'name'     => 'Trad trade definition trade ID',
  'select'   => 'T',
  'maxlen'   => 9,
  'sort'     => true
);
$opts['fdd']['trad_revenue_commission_sign'] = array(
  'name'     => 'Trad revenue commission sign',
  'select'   => 'T',
  'maxlen'   => 1,
  'sort'     => true
);
$opts['fdd']['trad_revenue_commission_amount'] = array(
  'name'     => 'Trad revenue commission amount',
  'select'   => 'T',
  'maxlen'   => 9,
  'sort'     => true
);
$opts['fdd']['trad_revenue_concession_sign'] = array(
  'name'     => 'Trad revenue concession sign',
  'select'   => 'T',
  'maxlen'   => 1,
  'sort'     => true
);
$opts['fdd']['trad_revenue_concession_amount'] = array(
  'name'     => 'Trad revenue concession amount',
  'select'   => 'T',
  'maxlen'   => 9,
  'sort'     => true
);
$opts['fdd']['trad_revenue_load_sign'] = array(
  'name'     => 'Trad revenue load sign',
  'select'   => 'T',
  'maxlen'   => 1,
  'sort'     => true
);
$opts['fdd']['trad_order_reference_number'] = array(
  'name'     => 'Trad order reference number',
  'select'   => 'T',
  'maxlen'   => 11,
  'sort'     => true
);
$opts['fdd']['trad_input_commission_sign'] = array(
  'name'     => 'Trad input commission sign',
  'select'   => 'T',
  'maxlen'   => 1,
  'sort'     => true
);
$opts['fdd']['trad_input_commission_amount'] = array(
  'name'     => 'Trad input commission amount',
  'select'   => 'T',
  'maxlen'   => 10,
  'sort'     => true
);
$opts['fdd']['trad_original_description_1'] = array(
  'name'     => 'Trad original description 1',
  'select'   => 'T',
  'maxlen'   => 20,
  'sort'     => true
);
$opts['fdd']['trad_original_description_2'] = array(
  'name'     => 'Trad original description 2',
  'select'   => 'T',
  'maxlen'   => 20,
  'sort'     => true
);
$opts['fdd']['trad_execution_time_a'] = array(
  'name'     => 'Trad execution time a',
  'select'   => 'T',
  'maxlen'   => 6,
  'sort'     => true
);
$opts['fdd']['trad_rr_enter_rep'] = array(
  'name'     => 'Trad rr enter rep',
  'select'   => 'T',
  'maxlen'   => 3,
  'sort'     => true
);
$opts['fdd']['trad_clearing_charge_sign'] = array(
  'name'     => 'Trad clearing charge sign',
  'select'   => 'T',
  'maxlen'   => 1,
  'sort'     => true
);
$opts['fdd']['trad_clearing_charge'] = array(
  'name'     => 'Trad clearing charge',
  'select'   => 'T',
  'maxlen'   => 9,
  'sort'     => true
);
$opts['fdd']['trad_execution_fee_sign'] = array(
  'name'     => 'Trad execution fee sign',
  'select'   => 'T',
  'maxlen'   => 1,
  'sort'     => true
);
$opts['fdd']['trad_execution_fee'] = array(
  'name'     => 'Trad execution fee',
  'select'   => 'T',
  'maxlen'   => 9,
  'sort'     => true
);
$opts['fdd']['trad_foreign_surcharge_sign'] = array(
  'name'     => 'Trad foreign surcharge sign',
  'select'   => 'T',
  'maxlen'   => 1,
  'sort'     => true
);
$opts['fdd']['trad_foreign_surcharge'] = array(
  'name'     => 'Trad foreign surcharge',
  'select'   => 'T',
  'maxlen'   => 8,
  'sort'     => true
);
$opts['fdd']['trad_super_branch'] = array(
  'name'     => 'Trad super branch',
  'select'   => 'T',
  'maxlen'   => 3,
  'sort'     => true
);

// Now important call to phpMyEdit
require_once 'phpMyEdit.class.php';
new phpMyEdit($opts);

?>


</body>
</html>