var TREE_ITEMS=[
												['Trades',0,{'tt':'Window object','sb':'Window object'},
												
												['Traded Symbols',0,{'tt':'Traded Symbols','sb':'Traded Symbols'},['ADS','?module=symbol&symbolval=ADS'],
['AMAT','?module=symbol&symbolval=AMAT'],
['ARB','?module=symbol&symbolval=ARB'],
['ARBA','?module=symbol&symbolval=ARBA'],
['ATML','?module=symbol&symbolval=ATML'],
['BEAS','?module=symbol&symbolval=BEAS'],
['BGO','?module=symbol&symbolval=BGO'],
['BRCD','?module=symbol&symbolval=BRCD'],
['CITI','?module=symbol&symbolval=CITI'],
['CKFR','?module=symbol&symbolval=CKFR'],
['CORV','?module=symbol&symbolval=CORV'],
['CSCO','?module=symbol&symbolval=CSCO'],
['DELL','?module=symbol&symbolval=DELL'],
['EFII','?module=symbol&symbolval=EFII'],
['FARM','?module=symbol&symbolval=FARM'],
['FD','?module=symbol&symbolval=FD'],
['FDO','?module=symbol&symbolval=FDO'],
['FIC','?module=symbol&symbolval=FIC'],
['FNM','?module=symbol&symbolval=FNM'],
['GILD','?module=symbol&symbolval=GILD'],
['HRB','?module=symbol&symbolval=HRB'],
['IBM','?module=symbol&symbolval=IBM'],
['INTC','?module=symbol&symbolval=INTC'],
['ISON','?module=symbol&symbolval=ISON'],
['JCOM','?module=symbol&symbolval=JCOM'],
['JDSU','?module=symbol&symbolval=JDSU'],
['JHF','?module=symbol&symbolval=JHF'],
['JNPR','?module=symbol&symbolval=JNPR'],
['KBH','?module=symbol&symbolval=KBH'],
['KDN','?module=symbol&symbolval=KDN'],
['KSU','?module=symbol&symbolval=KSU'],
['LEXR','?module=symbol&symbolval=LEXR'],
['LVLT','?module=symbol&symbolval=LVLT'],
['MSFT','?module=symbol&symbolval=MSFT'],
['ORCL','?module=symbol&symbolval=ORCL'],
['PCLE','?module=symbol&symbolval=PCLE'],
['SIRI','?module=symbol&symbolval=SIRI'],
['SPLS','?module=symbol&symbolval=SPLS'],
['SUNW','?module=symbol&symbolval=SUNW'],
['XATA','?module=symbol&symbolval=XATA'],
['XRX','?module=symbol&symbolval=XRX'],
['YHOO','?module=symbol&symbolval=YHOO'],
		],
	['Employee Trades',0,{'tt':'Trade in Employee Accounts','sb':'Trade in Employee Accounts'},['WATCH LIST (10 Trades)','?module=emptrades&listtype=watch'],['GRAY LIST (No Trades)','?module=emptrades&listtype=gray'],['RESTRICTED LIST (7 Trades)','?module=emptrades&listtype=restricted'],],