<?
include('../includes/dbconnect.php');
include('../includes/functions.php'); 
include('../includes/global.php'); 

//Function to determine Buy, Sell, Cover, Short
function compute_buy_sell ($val) {
	if (stripos($val,"P ") !== false) {
		return 'SS';
	} elseif (stripos($val,"R ") !== false) {
		return 'C';
	} else {
	 return 'X';
	}
}

//Move trade data from staging to production
$query_staging = "SELECT * from nfs_trades_raw";
$result_staging = mysql_query($query_staging) or die (mysql_error());

$row_inserted = 1;
while ( $row_staging = mysql_fetch_array($result_staging) ) {

		$computed_buy_sell = '';
		$get_bscss_val = compute_buy_sell ($row_staging['trad_confirm_legend_code']);
		
		if ($get_bscss_val == 'X') {
		$computed_buy_sell = $row_staging['trad_buy_sell'];
		} elseif ($get_bscss_val == 'SS' and ($row_staging['trad_sec_type']=='1' or $row_staging['trad_sec_type']=='2')) {
		$computed_buy_sell = $get_bscss_val;
		} elseif ($get_bscss_val == 'C' and ($row_staging['trad_sec_type']=='1' or $row_staging['trad_sec_type']=='2')) {
		$computed_buy_sell = $get_bscss_val;
		} else {
		$computed_buy_sell = $row_staging['trad_buy_sell'];
		}

$query_main = "INSERT INTO nfs_trades_test_new(
trad_firm,
trad_buy_sell,
trad_trade_date,
trad_settle_date,
trad_market_code,
trad_blotter_code,
trad_cancel_code,
trad_streetside_code,
trad_due_bill,
trad_correction_code,
trad_branch,
trad_account_number,
trad_full_account_number,
trad_account_type,
trad_country_code,
trad_cusip,
trad_basis_price_code,
trad_run_date,
trad_trade_reference_number,
trad_user_reference,
trad_canceled_combined_ref,
trad_batch,
trad_count,
trad_symbol,
trad_sec_type,
trad_sec_type_modifier,
trad_sec_type_calc,
trad_cns,
trad_primary_exchange,
trad_dtc_eligibility_code,
trad_foreign_code,
trad_registered_rep,
trad_state_country_code,
trad_ny_tax,
trad_sec_instructions,
trad_service,
trad_parent_account,
trad_agency_code,
trad_mode_del,
trad_proceed_instructions,
trad_income_instructions,
trad_sales_prod,
trad_trade_unit,
trad_short_name,
trad_acct_classification,
trad_citizen_code,
trad_country_of_tax_residency,
trad_transfer_legend_code,
trad_marketmaker_code,
trad_rr_penalty,
trad_minor_exec_broker,
trad_minor_clearing_broker,
trad_offset_account,
trad_offset_shortname,
trad_offset_rr,
trad_offset_commission,
trad_source,
trad_type_of_order,
trad_confirm_print,
trad_commission_accumulation,
trad_commission_schedule,
trad_blotter_override_code,
trad_nscc_code,
trad_commission_concession_code,
trad_quantity,
trad_price,
trad_alphaprice_dollar,
trad_alphaprice_space,
trad_alphaprice_fraction,
trad_plus_minus,
trad_principal,
trad_accrued_interest,
trad_trade_commission,
trad_state_tax,
trad_sec_fee,
trad_service_charge_misc_fee,
trad_net,
trad_brokerage,
trad_trade_concession,
trad_standard_commission,
trad_sec_desc_1,
trad_sec_desc_2,
trad_sec_desc_3,
trad_sec_desc_4,
trad_sec_desc_5,
trad_sec_desc_6,
trad_sec_desc_7,
trad_sec_desc_8,
trad_sec_desc_9,
trad_confirm_legend_code,
trad_rr_exec_rep,
trad_comm_discount_percent,
trad_strike_price,
trad_sec_group_code,
trad_due_bill_multiplier,
trad_d_market_code,
trad_d_blotter_code,
trad_commission_concession_code_a,
trad_commission_preference_code,
trad_fund_load_override,
trad_quantity_type,
trad_confirm_line,
trad_exchange_line,
trad_yield,
trad_yield_type,
trad_yield_date,
trad_yield_price,
trad_trading_away_code,
trad_major_clearing_broker,
trad_major_exec_broker,
trad_execution_time,
trad_branch_a,
trad_irs_no,
trad_market_place,
trad_market_sequence,
trad_market_override,
trad_time_in_force,
trad_auto_exec_code,
trad_issuer,
trad_issuer_type,
trad_bond_trader,
trad_bond_class_code,
trad_additional_markup,
trad_terminal_id,
trad_signon_rep_location,
trad_rr_signon_rep,
trad_rr_owning_rep,
trad_fund_load_percent,
trad_product_code,
trad_trading_flat_code,
trad_12B1_code,
trad_additional_fee_code_1,
trad_additional_fee_1,
trad_additional_fee_code_2,
trad_additional_fee_2,
trad_additional_fee_code_3,
trad_additional_fee_3,
trad_additional_fee_code_4,
trad_additional_fee_4,
trad_additional_fee_code_5,
trad_additional_fee_5,
trad_additional_fee_code_6,
trad_additional_fee_6,
trad_institutional_third_party,
trad_institutional_lot_number,
trad_bord_tord_code,
trad_mutual_fund_dtc_number,
trad_trade_entry,
trad_entry_sequence_number,
trad_solicited_code,
trad_elec_trade_id,
trad_rollup_count,
trad_revenue_clearing_charge_amt,
trad_revenue_misc_fee_amt,
trad_product_level,
trad_concession_code,
trad_purchase_type_code,
trad_trade_definition_type,
trad_trade_definition_trade_id,
trad_revenue_commission_sign,
trad_revenue_commission_amount,
trad_revenue_concession_sign,
trad_revenue_concession_amount,
trad_revenue_load_sign,
trad_order_reference_number,
trad_input_commission_sign,
trad_input_commission_amount,
trad_original_description_1,
trad_original_description_2,
trad_execution_time_a,
trad_rr_enter_rep,
trad_clearing_charge_sign,
trad_clearing_charge,
trad_execution_fee_sign,
trad_execution_fee,
trad_foreign_surcharge_sign,
trad_foreign_surcharge,
trad_super_branch)
values(".
"'".$row_staging['trad_firm']."',".
"'".$computed_buy_sell."',".
"'".$row_staging['trad_trade_date']."',".
"'".$row_staging['trad_settle_date']."',".
"'".$row_staging['trad_market_code']."',".
"'".$row_staging['trad_blotter_code']."',".
"'".$row_staging['trad_cancel_code']."',".
"'".$row_staging['trad_streetside_code']."',".
"'".$row_staging['trad_due_bill']."',".
"'".$row_staging['trad_correction_code']."',".
"'".$row_staging['trad_branch']."',".
"'".$row_staging['trad_account_number']."',".
"'".$row_staging['trad_branch'].$row_staging['trad_account_number']."',".
"'".$row_staging['trad_account_type']."',".
"'".$row_staging['trad_country_code']."',".
"'".$row_staging['trad_cusip']."',".
"'".$row_staging['trad_basis_price_code']."',".
"'".$row_staging['trad_run_date']."',".
"'".$row_staging['trad_trade_reference_number']."',".
"'".$row_staging['trad_user_reference']."',".
"'".$row_staging['trad_canceled_combined_ref']."',".
"'".$row_staging['trad_batch']."',".
"'".$row_staging['trad_count']."',".
"'".$row_staging['trad_symbol']."',".
"'".$row_staging['trad_sec_type']."',".
"'".$row_staging['trad_sec_type_modifier']."',".
"'".$row_staging['trad_sec_type_calc']."',".
"'".$row_staging['trad_cns']."',".
"'".$row_staging['trad_primary_exchange']."',".
"'".$row_staging['trad_dtc_eligibility_code']."',".
"'".$row_staging['trad_foreign_code']."',".
"'".$row_staging['trad_registered_rep']."',".
"'".$row_staging['trad_state_country_code']."',".
"'".$row_staging['trad_ny_tax']."',".
"'".$row_staging['trad_sec_instructions']."',".
"'".$row_staging['trad_service']."',".
"'".$row_staging['trad_parent_account']."',".
"'".$row_staging['trad_agency_code']."',".
"'".$row_staging['trad_mode_del']."',".
"'".$row_staging['trad_proceed_instructions']."',".
"'".$row_staging['trad_income_instructions']."',".
"'".$row_staging['trad_sales_prod']."',".
"'".$row_staging['trad_trade_unit']."',".
"'".str_replace("'","",$row_staging['trad_short_name'])."',".
"'".$row_staging['trad_acct_classification']."',".
"'".$row_staging['trad_citizen_code']."',".
"'".$row_staging['trad_country_of_tax_residency']."',".
"'".$row_staging['trad_transfer_legend_code']."',".
"'".$row_staging['trad_marketmaker_code']."',".
"'".$row_staging['trad_rr_penalty']."',".
"'".$row_staging['trad_minor_exec_broker']."',".
"'".$row_staging['trad_minor_clearing_broker']."',".
"'".$row_staging['trad_offset_account']."',".
"'".$row_staging['trad_offset_shortname']."',".
"'".$row_staging['trad_offset_rr']."',".
"'".substr($row_staging["trad_offset_commission"],0,5).".".substr($row_staging["trad_offset_commission"],5,2)."',".
"'".$row_staging['trad_source']."',".
"'".$row_staging['trad_type_of_order']."',".
"'".$row_staging['trad_confirm_print']."',".
"'".$row_staging['trad_commission_accumulation']."',".
"'".$row_staging['trad_commission_schedule']."',".
"'".$row_staging['trad_blotter_override_code']."',".
"'".$row_staging['trad_nscc_code']."',".
"'".$row_staging['trad_commission_concession_code']."',".
"'".substr($row_staging['trad_quantity'],0,11).".".substr($row_staging['trad_quantity'],11,5)."',".
"'".substr($row_staging['trad_price'],0,9).".".substr($row_staging['trad_price'],9,9)."',".
"'".$row_staging['trad_alphaprice_dollar']."',".
"'".$row_staging['trad_alphaprice_space']."',".
"'".$row_staging['trad_alphaprice_fraction']."',".
"'".substr($row_staging['trad_plus_minus'],0,9).".".substr($row_staging['trad_plus_minus'],9,9)."',".
"'".substr($row_staging['trad_principal'],0,13).".".substr($row_staging['trad_principal'],13,2)."',".
"'".substr($row_staging['trad_accrued_interest'],0,10).".".substr($row_staging['trad_accrued_interest'],10,2)."',".
"'".substr($row_staging['trad_trade_commission'],0,8).".".substr($row_staging['trad_trade_commission'],8,2)."',".
"'".substr($row_staging['trad_state_tax'],0,6).".".substr($row_staging['trad_state_tax'],6,2)."',".
"'".substr($row_staging['trad_sec_fee'],0,6).".".substr($row_staging['trad_sec_fee'],6,2)."',".
"'".substr($row_staging['trad_service_charge_misc_fee'],0,8).".".substr($row_staging['trad_service_charge_misc_fee'],8,2)."',".
"'".substr($row_staging['trad_net'],0,13).".".substr($row_staging['trad_net'],13,2)."',".
"'".substr($row_staging['trad_brokerage'],0,8).".".substr($row_staging['trad_brokerage'],8,2)."',".
"'".substr($row_staging['trad_trade_concession'],0,8).".".substr($row_staging['trad_trade_concession'],8,2)."',".
"'".substr($row_staging['trad_standard_commission'],0,8).".".substr($row_staging['trad_standard_commission'],8,2)."',".
"'".str_replace("'","\'",$row_staging['trad_sec_desc_1'])."',".
"'".str_replace("'","\'",$row_staging['trad_sec_desc_2'])."',".
"'".str_replace("'","\'",$row_staging['trad_sec_desc_3'])."',".
"'".str_replace("'","\'",$row_staging['trad_sec_desc_4'])."',".
"'".str_replace("'","\'",$row_staging['trad_sec_desc_5'])."',".
"'".str_replace("'","\'",$row_staging['trad_sec_desc_6'])."',".
"'".str_replace("'","\'",$row_staging['trad_sec_desc_7'])."',".
"'".str_replace("'","\'",$row_staging['trad_sec_desc_8'])."',".
"'".str_replace("'","\'",$row_staging['trad_sec_desc_9'])."',".
"'".$row_staging['trad_confirm_legend_code']."',".
"'".$row_staging['trad_rr_exec_rep']."',".
"'".substr($row_staging['trad_comm_discount_percent'],0,6).".".substr($row_staging['trad_comm_discount_percent'],6,4)."',".
"'".substr($row_staging['trad_strike_price'],0,6).".".substr($row_staging['trad_strike_price'],6,3)."',".
"'".$row_staging['trad_sec_group_code']."',".
"'".substr($row_staging['trad_due_bill_multiplier'],0,3).".".substr($row_staging['trad_due_bill_multiplier'],3,2)."',".
"'".$row_staging['trad_d_market_code']."',".
"'".$row_staging['trad_d_blotter_code']."',".
"'".$row_staging['trad_commission_concession_code_a']."',".
"'".$row_staging['trad_commission_preference_code']."',".
"'".substr($row_staging['trad_fund_load_override'],0,2).".".substr($row_staging['trad_fund_load_override'],2,2)."',".
"'".$row_staging['trad_quantity_type']."',".
"'".$row_staging['trad_confirm_line']."',".
"'".$row_staging['trad_exchange_line']."',".
"'".substr($row_staging['trad_yield'],0,2).".".substr($row_staging['trad_yield'],2,3)."',".
"'".$row_staging['trad_yield_type']."',".
"'".$row_staging['trad_yield_date']."',".
"'".substr($row_staging['trad_yield_price'],0,3).".".substr($row_staging['trad_yield_price'],3,3)."',".
"'".$row_staging['trad_trading_away_code']."',".
"'".$row_staging['trad_major_clearing_broker']."',".
"'".$row_staging['trad_major_exec_broker']."',".
"'".$row_staging['trad_execution_time']."',".
"'".$row_staging['trad_branch_a']."',".
"'".$row_staging['trad_irs_no']."',".
"'".$row_staging['trad_market_place']."',".
"'".$row_staging['trad_market_sequence']."',".
"'".$row_staging['trad_market_override']."',".
"'".$row_staging['trad_time_in_force']."',".
"'".$row_staging['trad_auto_exec_code']."',".
"'".$row_staging['trad_issuer']."',".
"'".$row_staging['trad_issuer_type']."',".
"'".$row_staging['trad_bond_trader']."',".
"'".$row_staging['trad_bond_class_code']."',".
"'".substr($row_staging['trad_additional_markup'],0,1).".".substr($row_staging['trad_additional_markup'],1,9)."',".
"'".$row_staging['trad_terminal_id']."',".
"'".$row_staging['trad_signon_rep_location']."',".
"'".$row_staging['trad_rr_signon_rep']."',".
"'".$row_staging['trad_rr_owning_rep']."',".
"'".substr($row_staging['trad_fund_load_percent'],0,2).".".substr($row_staging['trad_fund_load_percent'],2,2)."',".
"'".$row_staging['trad_product_code']."',".
"'".$row_staging['trad_trading_flat_code']."',".
"'".$row_staging['trad_12B1_code']."',".
"'".$row_staging['trad_additional_fee_code_1']."',".
"'".substr($row_staging['trad_additional_fee_1'],0,7).".".substr($row_staging['trad_additional_fee_1'],7,2)."',".
"'".$row_staging['trad_additional_fee_code_2']."',".
"'".substr($row_staging['trad_additional_fee_2'],0,7).".".substr($row_staging['trad_additional_fee_2'],7,2)."',".
"'".$row_staging['trad_additional_fee_code_3']."',".
"'".substr($row_staging['trad_additional_fee_3'],0,7).".".substr($row_staging['trad_additional_fee_3'],7,2)."',".
"'".$row_staging['trad_additional_fee_code_4']."',".
"'".substr($row_staging['trad_additional_fee_4'],0,7).".".substr($row_staging['trad_additional_fee_4'],7,2)."',".
"'".$row_staging['trad_additional_fee_code_5']."',".
"'".substr($row_staging['trad_additional_fee_5'],0,7).".".substr($row_staging['trad_additional_fee_5'],7,2)."',".
"'".$row_staging['trad_additional_fee_code_6']."',".
"'".substr($row_staging['trad_additional_fee_6'],0,7).".".substr($row_staging['trad_additional_fee_6'],7,2)."',".
"'".$row_staging['trad_institutional_third_party']."',".
"'".$row_staging['trad_institutional_lot_number']."',".
"'".$row_staging['trad_bord_tord_code']."',".
"'".$row_staging['trad_mutual_fund_dtc_number']."',".
"'".$row_staging['trad_trade_entry']."',".
"'".$row_staging['trad_entry_sequence_number']."',".
"'".$row_staging['trad_solicited_code']."',".
"'".$row_staging['trad_elec_trade_id']."',".
"'".$row_staging['trad_rollup_count']."',".
"'".substr($row_staging['trad_revenue_clearing_charge_amt'],0,5).".".substr($row_staging['trad_revenue_clearing_charge_amt'],5,2)."',".
"'".substr($row_staging['trad_revenue_misc_fee_amt'],0,5).".".substr($row_staging['trad_revenue_misc_fee_amt'],5,2)."',".
"'".$row_staging['trad_product_level']."',".
"'".$row_staging['trad_concession_code']."',".
"'".$row_staging['trad_purchase_type_code']."',".
"'".$row_staging['trad_trade_definition_type']."',".
"'".$row_staging['trad_trade_definition_trade_id']."',".
"'".$row_staging['trad_revenue_commission_sign']."',".
"'".substr($row_staging['trad_revenue_commission_amount'],0,5).".".substr($row_staging['trad_revenue_commission_amount'],5,2)."',".
"'".$row_staging['trad_revenue_concession_sign']."',".
"'".substr($row_staging['trad_revenue_concession_amount'],0,5).".".substr($row_staging['trad_revenue_concession_amount'],5,2)."',".
"'".$row_staging['trad_revenue_load_sign']."',".
"'".$row_staging['trad_order_reference_number']."',".
"'".$row_staging['trad_input_commission_sign']."',".
"'".$row_staging['trad_input_commission_amount']."',".
"'".$row_staging['trad_original_description_1']."',".
"'".$row_staging['trad_original_description_2']."',".
"'".$row_staging['trad_execution_time_a']."',".
"'".$row_staging['trad_rr_enter_rep']."',".
"'".$row_staging['trad_clearing_charge_sign']."',".
"'".substr($row_staging['trad_clearing_charge'],0,5).".".substr($row_staging['trad_clearing_charge'],5,2)."',".
"'".$row_staging['trad_execution_fee_sign']."',".
"'".substr($row_staging['trad_execution_fee'],0,5).".".substr($row_staging['trad_execution_fee'],5,2)."',".
"'".$row_staging['trad_foreign_surcharge_sign']."',".
"'".substr($row_staging['trad_foreign_surcharge'],0,4).".".substr($row_staging['trad_foreign_surcharge'],4,2)."',".
"'".$row_staging['trad_super_branch']."')";

  $result_main = mysql_query($query_main) or die("<b>A fatal Database (MySQL) error occured</b>.\n<br />Query: " . $query_main . "<br />\nError: (" . mysql_errno() . ") " . mysql_error());
  //echo "Trade Rows inserted: ".$row_inserted."\n";
  $row_inserted = $row_inserted + 1;

 
}	 
?>